name: G-Test
on: [push]

jobs:
  build:
    name: gtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install gtest libraries
        run: sudo apt-get install libgtest-dev
      - name: gtest code
        run: make test -c 3_Implementation
